# Global Supabase config
project_id = "vacokylwmswklrlsjynq"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_schemas = []
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
port = 9999
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_signin = false

[storage]
enabled = true
port = 54323
image_transformation = true

[edge_functions]
enabled = true
port = 54324

[analytics]
enabled = false
